version: "3.7"

services:
  extensions:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: extensions
    container_name: extensions-server
    depends_on: 
      - access-lib
    expose:
      - 9021
    ports:
      - 9021:9021
    volumes:
      - extensions-data-volume:/home/docker/html
      - ${EXTENSIONS}/src:/home/docker/geoportal-extensions/src
      - ${EXTENSIONS}/test:/home/docker/geoportal-extensions/test
      - ${EXTENSIONS}/test_rendering:/home/docker/geoportal-extensions/test_rendering
      - ${EXTENSIONS}/samples-src:/home/docker/geoportal-extensions/samples-src
    networks:
      - api-network

  access-lib:
    build:
      context: ${ACCESSLIB}
      dockerfile: ./docker/Dockerfile
    image: access-lib
    container_name: access-lib-server
    expose:
      - 9012
      - 9013
    ports:
      - 9012:9012
      - 9013:9013
    volumes:
      - extensions-data-volume:/home/docker/html
      - ${ACCESSLIB}/src:/home/docker/geoportal-access-lib/src
      - ${ACCESSLIB}/test:/home/docker/geoportal-access-lib/test
      - ${ACCESSLIB}/samples-src:/home/docker/geoportal-access-lib/samples-src
    networks:
      - api-network
    
  
  nginx:
    image: nginx:1.17.9
    container_name: nginx-server
    command: nginx-debug -g 'daemon off;'
    ports:
      - 8081:80
    volumes:
      - ./conf/default:/etc/nginx/sites-enabled/default:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - extensions-data-volume:/var/www/html
    networks:
      - api-network

volumes:
  extensions-data-volume:
    name: extensions-data-volume

networks:
  api-network:
    name: api-network
    driver: bridge
    ipam:
      driver: default